init:
  - git config --global core.autocrlf input
environment:
  VisualStudioVersion: 12.0
  
before_build:  
   set PATH=C:\Program Files (x86)\MSBuild\12.0\Bin;%PATH%  
  
build_script:
  - cmd: build.cmd
test: off
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
