init:
  - git config --global core.autocrlf input
before_build:
  - cmd: msiexec.exe /i /jm "lib\Pex\pex.academic.x86.msi" /quiet /norestart
build_script:
  - cmd: build.cmd
test: off
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
